services:
  directus:
    image: directus/directus
    container_name: directus
    ports:
      - "8055:8055"
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      WEBSOCKETS_ENABLED: "true"
      DB_CLIENT: "sqlite3"
    volumes:
      - ./uploads:/directus/uploads
      - directus-db:/directus/database
volumes:
  directus-db: {}